/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyDomainsRouteImport } from './routes/my-domains'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainNameRouteImport } from './routes/domain.$name'

const MyDomainsRoute = MyDomainsRouteImport.update({
  id: '/my-domains',
  path: '/my-domains',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainNameRoute = DomainNameRouteImport.update({
  id: '/domain/$name',
  path: '/domain/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$name': typeof DomainNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$name': typeof DomainNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faucet': typeof FaucetRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-domains': typeof MyDomainsRoute
  '/domain/$name': typeof DomainNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faucet' | '/leaderboard' | '/my-domains' | '/domain/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faucet' | '/leaderboard' | '/my-domains' | '/domain/$name'
  id:
    | '__root__'
    | '/'
    | '/faucet'
    | '/leaderboard'
    | '/my-domains'
    | '/domain/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaucetRoute: typeof FaucetRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyDomainsRoute: typeof MyDomainsRoute
  DomainNameRoute: typeof DomainNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-domains': {
      id: '/my-domains'
      path: '/my-domains'
      fullPath: '/my-domains'
      preLoaderRoute: typeof MyDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$name': {
      id: '/domain/$name'
      path: '/domain/$name'
      fullPath: '/domain/$name'
      preLoaderRoute: typeof DomainNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaucetRoute: FaucetRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyDomainsRoute: MyDomainsRoute,
  DomainNameRoute: DomainNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
